name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.15.4'
      
      - name: Cache Node.js modules
        uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create extension package
        run: npm run package
      
      - name: Upload the package as artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: abs-vs-code
          path: '*.vsix'
