---
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: '14'
        - id: get_version
          uses: battila7/get-version-action@v2
        - name: Install dependencies
          run: npm ci
        - name: Build the extension
          run: |
            npm run package
            mv *.vsix "abs-vs-code-${{ steps.get_version.outputs.version-without-v }}.vsix"
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ steps.get_version.outputs.version }}
            draft: false
            prerelease: false
        - name: Upload Release asset 
          id: upload_release_asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: "./abs-vs-code-${{ steps.get_version.outputs.version }}.vsix"
            asset_name: "abs-vs-code-${{ steps.get_version.outputs.version }}.vsix"
            asset_content_type: application/zip
